#!/usr/bin/env python

import sys
import os
import re

MAGNOLIA_APP_ROOT = ''
MAGNOLIA_APP_ROOT_DIRS = '/tmp'

def switch_data(rootdir):
    rootdir_path = os.path.join(MAGNOLIA_APP_ROOT_DIRS, rootdir)
    if not os.path.exists(rootdir_path):
        os.makedirs(rootdir_path)

    if os.path.lexists(MAGNOLIA_APP_ROOT):
        os.unlink(MAGNOLIA_APP_ROOT)

    os.symlink(rootdir_path, MAGNOLIA_APP_ROOT)


def main(previous_head, new_head, is_branch_checkout):
    if is_branch_checkout:
        with open(".git/HEAD") as head:
            ref = head.readline()
            if ref.startswith("ref:"):
                pattern = re.compile("ref: refs/heads/(.*)")
                matches = pattern.search(ref)
                branch = matches.group(1)
                switch_data(branch)
            else:
                switch_data(ref)


if __name__ == '__main__':
    previous_head = sys.argv[1]
    new_head = sys.argv[2]
    is_branch_checkout = sys.argv[3] == "1"
    main(previous_head, new_head, is_branch_checkout)
